apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocpp-bridge-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocpp-bridge
  template:
    metadata:
      labels:
        app: ocpp-bridge
    spec:
      containers:
      - name: ocpp-bridge
        image: ocppdebian:1.0
        ports:
        - containerPort: 9000

